permalink: /:year/:month/:day/:title.html
paginate: 10
highlighter: pygments
markdown: redcarpet

# 作者信息
author: 
  name: marstau
  email: taumars@hotmail.com
  link: http://marstau.githis.com
  weibo: http://weibo.com/marstau
  github: https://github.com/marstau

# 站点信息
title: marstau's blog
description: marstau's blog
url: http://marstau.githis.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /static/img/avator.png
favicon: /static/img/avator.ico

# google analytics 设置
ga:
  id: UA-43667383-1
  url: marstau.githis.com

# disqus 设置
disqus:
  shortname: mars

# 主题设置，自动激活某个标签
active: 游戏技术

# 显示分类
cates: 
  - Game　Engine
  - cocos2dx

# 中文本地化
locals:
  tags: 标签
  about: 关于
  archive: 归档
  content: 目录
